/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cjmur' at '1/25/17 8:25 PM' with Gradle 3.0
 *
 * @author cjmur, @date 1/25/17 8:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
